#!/usr/bin/env bash

get_record_info() {
	local domain=$1
	local subdomain=$2
	local record_info=$(dig $subdomain.$domain +short)
	local record_type=$(echo $record_info | awk '{print toupper($1)}')
	local destination=$(echo $record_info | awk '{print $2}')
	echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [[ -z $subdomain ]]; then
	get_record_info $domain www
	get_record_info $domain lb-01
	get_record_info $domain web-01
	get_record_info $domain web-02
else
	get_record_info $domain $subdomain
fi
