#!/usr/bin/env bash
# Listening Ports and Associated Programs

echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
ss -lntp | awk '{if ($5 == "LISTEN") print $1, $2, $3, $4, $5, $6, $7}'
echo ""
echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
ss -lx | awk '{if ($5 == "LISTEN") print $1, $2, $3, $4, $5, $6, $7, $8}'

