#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely

pid=$(ps -ef | grep "./4-to_infinity_and_beyond" | grep -v grep | awk '{print $2}')

if [ ! -z "$pid" ]; then
  kill -INT $pid
fi
