#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd

file=/etc/passwd

while read -r line
do
	username=$(echo "$line" | cut -d: -f1)
	userid=$(echo "$line" | cut -d: -f3)
	homedir=$(echo "$line" | cut -d: -f6)
	echo "$username:$userid:$homedir"

done < $file
