#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes

i=0
while [ $i -le 12 ];
do
	j=1
	echo "Hour: $i"
	while [ $j -lt 60 ];
	do
		echo $j
		j=$((j + 1))
	done
	i=$((i + 1))
done
