#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server

# Modify /etc/hosts file
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

# Flush the DNS cache
sudo service network-manager restart

