#!/usr/bin/env bash
# Listen on port 98

# Check if the user has sufficient permissions to run the script
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root or with sudo."
  exit 1
fi

# Listen on port 98 using netcat
nc -l 98

